// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './noto-sans-jp-kana.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Noto Sans JP Tegaki 3c1e5375',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Noto Sans JP Tegaki 3c1e5375'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1160,
  descender: -288,
  glyphData,
} as const;

export default bundle;
